<?php
/**
*
* @package language
* @copyright (c) 2007 phpBB Group
* @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
*
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine
//
// Some characters you may want to copy&paste:
// ’ » “ ” …
//

$lang = array_merge($lang, array(
	'TRANSLATION_INFO'	=> 'Slovenský preklad - PepeLopez',
	'DIRECTION'		=> 'ltr',
	'DATE_FORMAT'		=> '|d M Y|',	// 01 Jan 2007 (with Relative days enabled)
	'DATETIME_FORMAT'	=> '|d M Y, H:i|',	// 01 Jan 2007, 13:37 (with Relative days enabled)
	'USER_LANG'		=> 'sk-SK',

	// You can define different rules for the determination of plural forms here.
	// See http://wiki.phpbb.com/Plural_Rules for more information
	// or ask the translation manager for help.
	'PLURAL_RULE'		=> 8,

	'1_DAY'			=> '1 deň',
	'1_MONTH'		     => '1 mesiac',
	'1_YEAR'		     => '1 rok',
	'2_WEEKS'		     => '2 týždne',
	'3_MONTHS'		=> '3 mesiace',
	'6_MONTHS'		=> '6 mesiacov',
	'7_DAYS'		     => '7 dní',

	'ACCOUNT_ALREADY_ACTIVATED'		=> 'Váš účet už bol aktivovaný.',
	'ACCOUNT_DEACTIVATED'			=> 'Váš účet bol manuálne deaktivovaný a môže byť znovu aktivovaný len administrátorom.',
	'ACCOUNT_NOT_ACTIVATED'			=> 'Váš účet ešte nebol aktivovaný.',
	'ACP'						=> 'Administrátorský panel',
	'ACP_SHORT'					=> 'Administrátorský panel',
	'ACTIVE'						=> 'aktívny',
	'ACTIVE_ERROR'					=> 'Váš účet bol vytvorený, ale pravdepodobne ešte nebol aktivovaný. Ak máte problémy s aktiváciou, kontaktujte administrátora.',
	'ADMINISTRATOR'				=> 'Administrátor',
	'ADMINISTRATORS'				=> 'Administrátori',
	'AGE'						=> 'Vek',
	'AIM'						=> 'AIM',
	'AJAX_ERROR_TITLE'				=> 'Chyba AJAXu',
	'AJAX_ERROR_TEXT'				=> 'Chyba počas vykonávania akcie.',
	'AJAX_ERROR_TEXT_ABORT'			=> 'Užívateľom prerušená akcia.',
	'AJAX_ERROR_TEXT_TIMEOUT'		=> 'Vypršal časový limit pre vykonanie akcie. Pre správne dokončenie úkonu, akciu zopakujte.',
	'AJAX_ERROR_TEXT_PARSERERROR'	     => 'Chyba počas vykonávania akcie, pričom server vrátil nesprávnu odpoveď.',
	'ALLOWED'						=> 'Povolené',
	'ALL_FILES'					=> 'Všetky súbory',
	'ALL_FORUMS'					=> 'Všetky fóra',
	'ALL_MESSAGES'					=> 'Všetky správy',
	'ALL_POSTS'					=> 'Všetky príspevky',
	'ALL_TIMES'					=> 'Všetky časy sú v <abbr title="%2$s">%1$s</abbr>',
	'ALL_TOPICS'					=> 'Všetky témy',
	'AND'						=> 'A',
	'ARE_WATCHING_FORUM'			=> 'Budete upozornený na nové príspevky v tomto fóre.',
	'ARE_WATCHING_TOPIC'			=> 'Budete upozornený na nové príspevky v tejto téme.',
	'ASCENDING'					=> 'vzostupne',
	'ATTACHMENTS'					=> 'Prílohy',
	'ATTACHED_IMAGE_NOT_IMAGE'		=> 'Súbor s obrázkom, ktorý sa pokúšate vložiť ako prílohu je neplatný.',
	'AUTHOR'						=> 'Autor',
	'AUTH_NO_PROFILE_CREATED'		=> 'Vytvorenie užívateľského profilu neúspešné.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_ENTRY'              => 'Systémová chyba. Neplatný záznam databázy.',
	'AUTH_PROVIDER_OAUTH_ERROR_INVALID_SERVICE_TYPE'	     => 'Systémová chyba. Obslužnej rutine OAuth poskytnutá nesprávna služba.',
	'AUTH_PROVIDER_OAUTH_ERROR_SERVICE_NOT_CREATED'	     => 'Systémová chyba. Služba OAuth nevytvorená',
	'AUTH_PROVIDER_OAUTH_SERVICE_BITLY'			     => 'Bitly',
	'AUTH_PROVIDER_OAUTH_SERVICE_FACEBOOK'			     => 'Odkaz na Facebook',
	'AUTH_PROVIDER_OAUTH_SERVICE_GOOGLE'			     => 'Google',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_NOT_STORED'		     => 'Systémová chyba. OAuth token neuložený.',
	'AUTH_PROVIDER_OAUTH_TOKEN_ERROR_INCORRECTLY_STORED'   => 'Systémová chyba. OAuth token uložený nesprávne.',
	'AVATAR_DISALLOWED_CONTENT'		=> 'Odovzdávanie súboru bolo zamietnuté, pretožo bolo vyhodnotené ako podozrivý útok.',
	'AVATAR_DISALLOWED_EXTENSION'	     => 'Tento súbor nemôže byť zobrazený, pretože prípona <strong>%s</strong> je pre tento portál zablokovaná.',
	'AVATAR_EMPTY_REMOTE_DATA'		=> 'Vzdialený obrázok profilu nemôže byť odovzdaný, pravdepodobne je poškodený.',
	'AVATAR_EMPTY_FILEUPLOAD'		=> 'Odovzdaný súbor obrázku profilu je prázdny.',
	'AVATAR_INVALID_FILENAME'		=> '%s má neplatný názov súboru.',
	'AVATAR_NOT_UPLOADED'			=> 'Obrázok profilu nemôže byť odovzdaný.',
	'AVATAR_NO_SIZE'				=> 'Nebolo možné získať rozmery obrázku. Zadajte ich ručne.',
	'AVATAR_PARTIAL_UPLOAD'			=> 'Vybratý súbor bol odovzdaný len čiastočne.',
	'AVATAR_PHP_SIZE_NA'			=> 'Súbor s avatarom je príliš veľký.<br />Nie je možné zistiť povolený limit veľkosti zo súboru php.ini.',
	'AVATAR_PHP_SIZE_OVERRUN'		=> 'Súbor s avatarom je príliš veľký. Limit je %1$d %2$s.<br />Toto je hodnota nastavená systémom.',
	'AVATAR_REMOTE_UPLOAD_TIMEOUT'	=> 'Obrázok profilu nemôže byť odovzdaný. Vypršal čas spojenia.',
	'AVATAR_URL_INVALID'			=> 'URL adresa, ktorú ste zadali je neplatná.',
	'AVATAR_URL_NOT_FOUND'			=> 'Súbor nenájdený.',
	'AVATAR_WRONG_FILESIZE'			=> 'Súbor s avatarom, musí mať najmenej 0 a najviac %1$d %2$s.',
	'AVATAR_WRONG_SIZE'				=> 'Obrázok profilu má rozmery %5$s x %6$s. Avatar musí byť mať rozmery najmenej %1$s x %2$s a najviac %3$s x %4$s.',

	'BACK_TO_TOP'			=> 'Hore',
	'BACK_TO_PREV'			=> 'Späť na predchádzajúcu stranu',
	'BAN_TRIGGERED_BY_EMAIL' => 'Na vašu emailovú adresu sa vzťahuje zákaz vstupu na tento portál.',
	'BAN_TRIGGERED_BY_IP'	=> 'Na vašu IP sa vzťahuje zákaz vstupu na tento portál.',
	'BAN_TRIGGERED_BY_USER'	=> 'Na vaše užívateľské meno sa vzťahuje zákaz vstupu na tento portál.',
	'BBCODE_GUIDE'			=> 'Príručka BBCode',
	'BCC'				=> 'BCC',
	'BIRTHDAYS'			=> 'Narodeniny',
	'BOARD_BAN_PERM'		=> 'Bol vám <strong>trvale</strong> zakázaný prísup na tento portál.<br /><br />Pre získanie ďalších informácií kontaktujte %2$sadministrátora%3$s.',
	'BOARD_BAN_REASON'		=> 'Dôvod: <strong>%s</strong>',
	'BOARD_BAN_TIME'		=> 'Do <strong>%1$s</strong> vám bol zakázaný prístup na tento portál.<br /><br />Pre získanie ďalších informácií kontaktujte %2$sadministrátora%3$s.',
	'BOARD_DISABLE'		=> 'Toto fórum je momentálne nedostupné.',
	'BOARD_DISABLED'		=> 'Toto fórum je momentálne neprístupné.',
	'BOARD_UNAVAILABLE'		=> 'Toto fórum je dočasne nedostupné.',
	'BROWSING_FORUM'		=> 'Užívatelia prezerajúci toto fórum: %1$s',
	'BROWSING_FORUM_GUESTS'	=> array(
		1	=> 'Užívatelia prezerajúci toto fórum: %2$s a %1$d neregistrovaný',
		2	=> 'Užívatelia prezerajúci toto fórum: %2$s a %1$d neregistrovaní',
          3	=> 'Užívatelia prezerajúci toto fórum: %2$s a %1$d neregistrovaných',
	),
	'BUTTON_EDIT'			=> 'Upraviť',
	'BUTTON_FORUM_LOCKED'	=> 'Zamknuté',
	'BUTTON_NEW_TOPIC'		=> 'Založiť novú tému',
	'BUTTON_PM'			=> 'PM',
	'BUTTON_PM_FORWARD'		=> 'Poslať ďalej',
	'BUTTON_PM_NEW'		=> 'Napísať správu',
	'BUTTON_PM_REPLY'		=> 'Odoslať odpoveď',
	'BUTTON_PM_REPLY_ALL'	=> 'Odpovedať všetkým',
	'BUTTON_POST_REPLY'		=> 'Napísať odpoveď',
	'BUTTON_QUOTE'			=> 'Citovať',
	'BUTTON_TOPIC_LOCKED'	=> 'Zamknuté',
	'BYTES'				=> 'Bajtov',
	'BYTES_SHORT'			=> 'B',

	'CANCEL'				=> 'Zrušiť',
	'CHANGE'				=> 'Zmeniť',
	'CHANGE_FONT_SIZE'		=> 'Zmeniť veľkosť písma',
	'CHANGING_PREFERENCES'	=> 'Zmeniť nastavenia portálu',
	'CHANGING_PROFILE'		=> 'Zmeniť profilové nastavenia',
	'CHARACTERS'			=> array(
		1	=> '%d znak',
		2	=> '%d znaky',
          3    => '%d znakov',
	),
	'COLLAPSE_VIEW'		=> 'Rozbaliť',
	'CLOSE_WINDOW'			=> 'Zavrieť okno',
	'COLOUR_SWATCH'		=> 'Paleta farieb',
	'COLON'				=> ':',
	'COMMA_SEPARATOR'		=> ', ',	// Comma used to join lists into a single string, use localised comma if appropriate, eg: Ideographic or Arabic
	'CONFIRM'				=> 'Potvrdiť',
	'CONFIRM_CODE'			=> 'Potvrdzovací kód',
	'CONFIRM_CODE_EXPLAIN'	=> 'Opíšte kód. Rozlišujte malé a veľké písmená.',
	'CONFIRM_CODE_WRONG'	=> 'Zadaný potvrdzovací kód je nesprávny.',
	'CONFIRM_OPERATION'		=> 'Ste si istý, že chcete vykonať túto operáciu?',
	'CONFIRM_AVATAR_DELETE'  => 'Ste si istý, že chcete odstrániť tento obrázok profilu?',
	'CONGRATULATIONS'		=> 'Blahoželanie',
	'CONNECTION_FAILED'		=> 'Spojenie prerušené.',
	'CONNECTION_SUCCESS'	=> 'Spojenie úspešné!',
	'CONTACT'				=> 'Kontaktovať užívateľa',
	'CONTACT_USER'			=> 'Kontaktné informácie užívateľa - %s',
	'CONTACT_US'			=> 'Napísať administrátorovi',
	'COOKIES_DELETED'		=> 'Cookies vymazané.',
	'CURRENT_TIME'			=> 'Je %s',

	'DAY'					=> 'Deň',
	'DAYS'					=> 'Dní',
	'DELETE'				=> 'Vymazať',
	'DELETE_ALL'			=> 'Vymazať všetko',
	'DELETE_COOKIES'		=> 'Vymazať cookies',
	'DELETE_MARKED'		=> 'Zmazať označené',
	'DELETE_POST'			=> 'Zmazať príspevok',
	'DELIMITER'			=> 'Oddelovač',
	'DESCENDING'			=> 'zostupne',
	'DISABLED'			=> 'Zablokované',
	'DISPLAY'				=> 'Zobraziť',
	'DISPLAY_GUESTS'		=> 'Zobraziť neregistrovaných',
	'DISPLAY_MESSAGES'		=> 'Zobraziť správy za',
	'DISPLAY_POSTS'		=> 'Zobraziť príspevky za',
	'DISPLAY_TOPICS'		=> 'Zobraziť témy za',
	'DOWNLOADED'			=> 'Stiahnuté',
	'DOWNLOADING_FILE'		=> 'Sťahujem súbor',
	'DOWNLOAD_COUNTS'		=> array(
		1	=> '%d stiahnutie',
		2	=> '%d stiahnutia',
          3    => '%d stiahnutí',
	),

	'EDIT_POST'						=> 'Úprava príspevku',
	'ELLIPSIS'						=> '…',
	'EMAIL'							=> 'Email', // Short form for EMAIL_ADDRESS
	'EMAIL_ADDRESS'					=> 'Emailová adresa',
	'EMAIL_INVALID_EMAIL'				=> 'Uvedená emailová adresa nie je platná.',
	'EMAIL_SMTP_ERROR_RESPONSE'			=> 'Systémová chyba pri odosielaní emailu na riadku <strong>%1$s</strong>. Odpoveď: %2$s.',
	'EMPTY_SUBJECT'					=> 'Ak zakladáte novú tému, musíte zadať predmet.',
	'EMPTY_MESSAGE_SUBJECT'				=> 'Ak vytvárate novú správu musíte zadať predmet.',
	'ENABLED'							=> 'Povolené',
	'ENCLOSURE'						=> 'Uzatvorenie',
	'ENTER_USERNAME'					=> 'Vložte užívateľské meno',
	'ERR_CHANGING_DIRECTORY'			     => 'Nie je možné zmeniť adresár.',
	'ERR_CONNECTING_SERVER'				=> 'Chyba pri pripojení k serveru.',
	'ERR_JAB_AUTH'						=> 'Nedá sa prihlásiť k serveru Jabber.',
	'ERR_JAB_CONNECT'					=> 'Nedá sa pripojiť k serveru Jabber.',
	'ERR_UNABLE_TO_LOGIN'				=> 'Zadané prihlasovacie údaje sú nesprávne.',
	'ERR_UNWATCHING'					=> 'Pri odhlasovaní odberu noviniek sa vyskytla chyba.',
	'ERR_WATCHING'						=> 'Pri prihlasovaní odberu noviniek sa vyskytla chyba.',
	'ERR_WRONG_PATH_TO_PHPBB'			=> 'Systémová chyba. Zadaná cesta k phpBB je neplatná.',
	'ERROR'							=> 'Chyba',
	'EXPAND_VIEW'						=> 'Zbaliť',
	'EXTENSION'						=> 'Prípona',
	'EXTENSION_DISABLED'				=> 'Prípona <strong>%s</strong> nie je povolená.',
	'EXTENSION_DISABLED_AFTER_POSTING'	     => 'Prípona <strong>%s</strong> bola zablokovaná.',
	'EXTENSION_DOES_NOT_EXIST'			=> 'Prípona <strong>%s</strong> neexistuje.',

	'FACEBOOK'				=> 'Facebook',
	'FAQ'					=> 'FAQ',
	'FAQ_EXPLAIN'			     => 'Často kladené otázky',
	'FILENAME'				=> 'Názov súboru',
	'FILESIZE'				=> 'Veľkosť súboru',
	'FILEDATE'				=> 'Dátumová pečiatka súboru',
	'FILE_COMMENT'			=> 'Komentár k súboru',
	'FILE_CONTENT_ERR'		=> 'Obsah súboru %s sa nedá čítať.',
	'FILE_JSON_DECODE_ERR'	=> 'Dekódovanie JSON súboru neúspešné: %s',
	'FILE_NOT_FOUND'		=> 'Súbor nenájdený: %s',
	'FIND_USERNAME'		=> 'Vyhľadať užívateľa',
	'FOLDER'				=> 'Adresár',
	'FORGOT_PASS'			=> 'Zabudnuté heslo',
	'FORM_INVALID'			=> 'Odosielaný formulár je neplatný. Skúste odoslať znovu.',
	'FORUM'				=> 'Fórum',
	'FORUMS'				=> 'Fóra',
	'FORUMS_MARKED'		=> 'Všetky fóra boli označené ako prečítané.',
	'FORUM_CAT'			=> 'Kategória fóra',
	'FORUM_INDEX'			=> 'Obsah portálu',
	'FORUM_LINK'			=> 'Odkaz na fórum',
	'FORUM_LOCATION'		=> 'Činnosť',
	'FORUM_LOCKED'			=> 'Fórum zamknuté',
	'FORUM_RULES'			=> 'Pravidlá fóra',
	'FORUM_RULES_LINK'		=> 'Kliknite sem, ak chcete zobraziť pravidlá fóra',
	'FROM'				=> 'z',
	'FSOCK_DISABLED'		=> 'Operácia nemôže byť vykonaná, pretože <var>fsockopen</var> bola zablokovaná alebo cieľový server neodpovedá.',
	'FSOCK_TIMEOUT'		=> 'Časový limit čítania prúdu dát zo siete vypršal.',

	'FTP_FSOCK_HOST'			=> 'FTP host',
	'FTP_FSOCK_HOST_EXPLAIN'		=> 'FTP server použitý na pripojenie k vašej stránke.',
	'FTP_FSOCK_PASSWORD'		=> 'FTP heslo',
	'FTP_FSOCK_PASSWORD_EXPLAIN'	=> 'Heslo pre vaše užívateľské meno FTP.',
	'FTP_FSOCK_PORT'			=> 'FTP port',
	'FTP_FSOCK_PORT_EXPLAIN'		=> 'Port použitý na pripojenie k FTP serveru.',
	'FTP_FSOCK_ROOT_PATH'		=> 'Cesta k phpBB',
	'FTP_FSOCK_ROOT_PATH_EXPLAIN'	=> 'Cesta z koreňového adresára k phpBB.',
	'FTP_FSOCK_TIMEOUT'			=> 'FTP timeout',
	'FTP_FSOCK_TIMEOUT_EXPLAIN'	=> 'Časový limit v sekundách, počas ktorého bude systém čakať na odpoveď zo serveru.',
	'FTP_FSOCK_USERNAME'		=> 'FTP užívateľské meno',
	'FTP_FSOCK_USERNAME_EXPLAIN'	=> 'Užívateľské meno použité na pripojenie k vášmu kontu FTP serveru.',

	'FTP_HOST'				=> 'FTP host',
	'FTP_HOST_EXPLAIN'			=> 'FTP server použitý na pripojenie k vašej stránke.',
	'FTP_PASSWORD'				=> 'FTP heslo',
	'FTP_PASSWORD_EXPLAIN'		=> 'Heslo pre vaše užívateľské meno FTP.',
	'FTP_PORT'				=> 'FTP port',
	'FTP_PORT_EXPLAIN'			=> 'Port použitý na pripojenie k FTP serveru.',
	'FTP_ROOT_PATH'			=> 'Cesta k phpBB',
	'FTP_ROOT_PATH_EXPLAIN'		=> 'Cesta z koreňového adresára k phpBB.',
	'FTP_TIMEOUT'				=> 'FTP timeout',
	'FTP_TIMEOUT_EXPLAIN'		=> 'Časový limit v sekundách, počas ktorého bude systém čakať na odpoveď zo serveru.',
	'FTP_USERNAME'				=> 'FTP užívateľské meno',
	'FTP_USERNAME_EXPLAIN'		=> 'Užívateľské meno použité na pripojenie k vášmu kontu FTP serveru.',

	'GENERAL_ERROR'			=> 'Všeobecná chyba',
	'GB'						=> 'GB',
	'GIB'					=> 'GB',
	'GO'						=> 'Vykonaj',
	'GOOGLEPLUS'				=> 'Google+',
	'GOTO_FIRST_POST'			=> 'Preskočiť na prvý príspevok',
	'GOTO_LAST_POST'			=> 'Preskočiť na posledný príspevok',
	'GOTO_PAGE'				=> 'Preskočiť na stranu',
	'GROUP'					=> 'Skupina',
	'GROUPS'					=> 'Členstvo v skupinách',
	'GROUP_ERR_TYPE'			=> 'Bol zvolený nevhodný typ skupiny.',
	'GROUP_ERR_USERNAME'		=> 'Nebol zadaný názov skupiny.',
	'GROUP_ERR_USER_LONG'		=> 'Názov skupiny nesmie mať viac než 60 zankov. Zadaný názov je príliš dlhý.',
	'GUEST'					=> 'Neregistrovaný',
	'GUEST_USERS_ONLINE'		=> array(
          0	=> '',
          1	=> '| %d neregistrovaný',
		2	=> '| %d neregistrovaní',
          3	=> '| %d neregistrovaných',
	),
	'GUEST_USERS_TOTAL'			=> array(
          0	=> '',
          1	=> '| %d neregistrovaný',
		2	=> '| %d neregistrovaní',
          3	=> '| %d neregistrovaných',
	),
	'G_ADMINISTRATORS'			=> 'Administrátori',
	'G_BOTS'					=> 'Boti',
	'G_GUESTS'				=> 'Neregistrovaní',
	'G_REGISTERED'				=> 'Registrovaní užívatelia',
	'G_REGISTERED_COPPA'		=> 'Registrovaní COPPA užívatelia (mladistvý)',
	'G_GLOBAL_MODERATORS'		=> 'Globálny moderátori',
	'G_NEWLY_REGISTERED'		=> 'Novo registrovaní užívatelia',

	'HIDDEN_USERS_ONLINE'		=> array(
          0	=> '',
          1	=> '| %d skrytý',
		2	=> '| %d skrytí',
          3	=> '| %d skrytých',
	),
	'HIDDEN_USERS_TOTAL'		=> array(
          0	=> '',
          1	=> '| %d skrytý',
		2	=> '| %d skrytí',
          3	=> '| %d skrytých',
	),
	'HIDE_GUESTS'					=> 'Skryť neregistrovaných',
	'HIDE_ME'						=> 'Skrýť moju prítomnosť počas tohoto pripojenia',
	'HOURS'						=> 'Hodín',
	'HOME'						=> 'Domov',

	'ICQ'					=> 'ICQ',
	'IF'						=> 'Ak',
	'IMAGE'					=> 'Obrázok',
	'IMAGE_FILETYPE_INVALID'	     => 'Prípona súboru obrázku %d pre mimetyp %s nie je podporovaná.',
	'IMAGE_FILETYPE_MISMATCH'	=> 'Nesúhlasí typ súboru obrázku, očakáva sa prípona %1$s, ale bola zadaný obrázok s príponou %2$s.',
	'IN'						=> 'v',
	'INDEX'					=> 'Hlavná stránka',
	'INFORMATION'				=> 'Informácia',
	'INSECURE_REDIRECT'			=> 'Pokus o presmerovanie na potenciálne nebezpečnú stránku.',
	'INTERESTS'				=> 'Záujmy',
	'INVALID_DIGEST_CHALLENGE'	=> 'Neplatná požiadavka na spracovanie.',
	'INVALID_EMAIL_LOG'			=> 'Nie je <strong>%s</strong> neplatnou emailovou adresou?',
	'INVALID_PLURAL_RULE'		=> 'Zadaná hodnota plurálu je neplatná. Povolené sú hodnoty od 0 do 15.',
	'IP'						=> 'IP',
	'IP_BLACKLISTED'			=> 'Vaša IP adresa %1$s bola zablokovaná, pretože je uvedená na čiernej listine. Ďalšie informácie <a href="%2$s">%2$s</a>.',

	'JABBER'				=> 'Jabber',
	'JOINED'				=> 'Dátum registrácie',
	'JUMP_PAGE'			=> 'Zadajte číslo strany, ktorú chcete zobraziť',
	'JUMP_TO'				=> 'Rýchla navigácia vo fórach',
	'JUMP_TO_PAGE'			=> 'Prejsť na stránku',
	'JUMP_TO_PAGE_CLICK'	=> 'Kliknite aby ste prešli na stránku…',

	'KB'					=> 'kB',
	'KIB'				=> 'kB',

	'LAST_POST'						=> 'Posledný príspevok',
	'LAST_UPDATED'						=> 'Posledná aktualizácia',
	'LAST_VISIT'						=> 'Posledná návšteva',
	'LDAP_NO_LDAP_EXTENSION'			     => 'Rozšírenie LDAP nie je k dispozícii.',
	'LDAP_NO_SERVER_CONNECTION'			=> 'Nedá sa pripojiť k LDAP serveru.',
	'LDAP_SEARCH_FAILED'				=> 'Počas prehľadávania priečinku LDAP sa vyskytla chyba.',
	'LEGEND'							=> 'Legenda',
	'LIVE_SEARCHES_NOT_ALLOWED'			=> 'Živé vyhľadávanie je zablovované.',
	'LOADING'							=> 'Nahrávam',
	'LOCATION'						=> 'Bydlisko',
	'LOCK_POST'						=> 'Zamknúť príspevok',
	'LOCK_POST_EXPLAIN'					=> 'Zabrániť úprave',
	'LOCK_TOPIC'						=> 'Zamknúť tému',
	'LOGIN'							=> 'Prihlásiť sa',
	'LOGIN_CHECK_PM'					=> 'Ak chcete zobraziť vaše súkromné správy musíte byť prihlásený.',
	'LOGIN_CONFIRMATION'				=> 'Potvrdenie prihlásenia',
	'LOGIN_CONFIRM_EXPLAIN'				=> 'V snahe zamedziť útokom na užívateľské účty vyžaduje portál po prekročení maximálneho počtu pokusov o prihlásenie zadanie potvrzovacieho kódu. Opíšte kód z obrázku. Ak to nedokážete, kontaktujte prosm %sadministrátorov portálu%s.', // unused
	'LOGIN_ERROR_ATTEMPTS'				=> 'Prekročili ste maximálny počet pokusov o prihlásenie. Teraz musíte okrem zadania mena a hesla opísať aj kód z obrázku.',
	'LOGIN_ERROR_EXTERNAL_AUTH_APACHE'	     => 'Nebol ste autorizovaný Apachom.',
	'LOGIN_ERROR_OAUTH_SERVICE_DOES_NOT_EXIST'	=> 'Systémová chyba. Bola vyžiadaná neexistujúca služba OAuth.',
	'LOGIN_ERROR_PASSWORD'				=> 'Zadané heslo nie je platné. Pri ďalšom pokuse o prihlásenie pozorne skontrolujte vkladanie hesla. Ak problém pretrváva kontaktujte %sadministrátorov portálu%s.',
	'LOGIN_ERROR_PASSWORD_CONVERT'		=> 'Ospravedlňujeme sa, ale počas aktualizácie softvéru portálu nebolo možné previesť vaše súčasné heslo. Prosím použite funkciu %svyžiadania nového hesla%s. Ak problém pretrváva kontaktujte %sadministrátorov portálu%s.',
	'LOGIN_ERROR_USERNAME'				=> 'Zadané užívateľské meno nie je platné. Pri ďalšom pokuse o prihlásenie pozorne skontrolujte vkladanie hesla. Ak problém pretrváva kontaktujte %sadministrátorov portálu%s.',
	'LOGIN_FORUM'						=> 'Fórum, je chránené heslom. Pre zobrazenie alebo vkladanie príspevkov do tohoto fóra je požadované heslo fóra.',
	'LOGIN_INFO'						=> 'Ak sa chcete prihlásiť musíte byť najprv zaregsitrovaný. Registrácia trvá len pár sekúnd a dáva vám väčšie možnosti. Administrátor fóra môže prideľovať registrovaným užívateľom rozšířené právomoci. Pred registraciou se uistite, že ste sa oboznámili s podmienkami pre používanie tohoto fóra a s dalšími pravidlami. Tiež sa uistite, že si prečítate akékoľvek budúce pravidlá, ktoré sa na tomto fóre môžu objaviť.',
	'LOGIN_VIEWFORUM'					=> 'Portál vyžaduje, aby ste boli zaregistrovaný a prihlásený, ak chcete zobraziť obsah tohoto fóra.',
	'LOGIN_EXPLAIN_EDIT'				=> 'Ak chcete upraviť príspevky v tomto fóre, musíte byť zaregistrovaný a prihlásený.',
	'LOGIN_EXPLAIN_VIEWONLINE'			=> 'Ak chcete zobraziť zoznam online užívateľov, musíte byť zaregistrovaný a prihlásený.',
	'LOGIN_REQUIRED'					=> 'Ak chcete vykonať túto akciu musíte byť prihlásený.',
	'LOGOUT'							=> 'Odhlásiť sa',
	'LOGOUT_USER'						=> 'Odhlásiť sa ako [%s]',
	'LOG_ME_IN'						=> 'V budúcnosti ma automaticky prihlásiť',

	'MAIN'				=> 'Hlavné',
	'MARK'				=> 'Označiť',
	'MARK_ALL'			=> 'Označiť všetko',
	'MARK_ALL_READ'		=> 'Označiť všetko ako prečítané',
	'MARK_FORUMS_READ'		=> 'Označiť všetky fóra ako prečítané',
	'MARK_READ'			=> 'Označiť ako prečítané',
	'MARK_SUBFORUMS_READ'	=> 'Označiť všetky subfóra ako prečítané',
	'MB'					=> 'MB',
	'MIB'				=> 'MB',
	'MCP'				=> 'Moderátorský panel',
	'MCP_SHORT'			=> 'Moderátorský panel',
	'MEMBERLIST'			=> 'Zoznam užívateľov',
	'MEMBERLIST_EXPLAIN'	=> 'Zobraziť úplný zoznam užívateľov',
	'MERGE'				=> 'Rozdeliť',
	'MERGE_POSTS'			=> 'Presunúť príspevky',
	'MERGE_TOPIC'			=> 'Spojiť tému',
	'MESSAGE'				=> 'Správa',
	'MESSAGES'			=> 'Správy',
	'MESSAGES_COUNT'		=> array( 
          1	=> '%d správa',
		2	=> '%d správy',
          3	=> '%d správ',
	),
	'MESSAGE_BODY'			=> 'Obsah správy',
	'MINUTES'				=> 'Minút',
	'MODERATE'			=> 'Moderovať',
	'MODERATOR'			=> 'Moderátor',
	'MODERATORS'			=> 'Moderátori',
	'MODULE_NOT_ACCESS'		=> 'Modul nie je prístupný',
	'MODULE_NOT_FIND'		=> 'Modul %s nenájdený',
	'MODULE_FILE_INCORRECT_CLASS'	=> 'Súbor modulu %s neobshauje požadovanú triedu [%s]',
	'MONTH'					=> 'Mesiac',
	'MOVE'					=> 'Presunúť',

	'NA'						=> 'Nepoužíva sa',
	'NEWEST_USER'				=> 'Najnovším registrovaným užívateľom je <strong>%s</strong>',
	'NEW_MESSAGE'				=> 'Nová správa',
	'NEW_MESSAGES'				=> 'Nové správy',
	'NEW_POST'					=> 'Nový príspevok',	// Not used anymore
	'NEW_POSTS'					=> 'Nové príspevky',	// Not used anymore
	'NEXT'						=> 'Ďalšia',		// Used in pagination
	'NEXT_STEP'					=> 'Ďalší krok',
	'NEVER'						=> 'Nikdy',
	'NO'						=> 'Nie',
	'NO_NOTIFICATIONS'			=> 'Nemáte žiadne upozornenia',
	'NOT_ALLOWED_MANAGE_GROUP'	=> 'Nemáte dostatočné oprávnenia na správu tejto skupiny.',
	'NOT_AUTHORISED'			=> 'Nemáte dostatočné oprávnenia na vstup do tejto časti.',
	'NOT_WATCHING_FORUM'		=> 'Sledovanie tohoto fóra ukončené.',
	'NOT_WATCHING_TOPIC'		=> 'Ukončené prijímanie upozornení na nové príspevky v tejto téme.',
	'NOTIFICATIONS'			=> 'Upozornenia',
	// This applies for NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	// %1$s will return a list of users that's concatenated using "," and "and" - see STRING_LIST
	// Once the user count reaches 5 users or more, the list is trimmed using NOTIFICATION_X_OTHERS
	// Once the user count reaches 20 users or more, the list is trimmed using NOTIFICATION_MANY_OTHERS
	// Examples:
	// A replied...
	// A and B replied...
	// A, B and C replied...
	// A, B, C and 2 others replied...
	// A, B, C and others replied...
	'NOTIFICATION_BOOKMARK'		=> array(
		1	=> '<strong>Nový príspevok</strong> od užívateľa %1$s v téme zo záložiek:',
          2	=> '<strong>Nové príspevky</strong> od užívateľov %1$s v téme zo záložiek:',
          3	=> '<strong>Nové príspevky</strong> od užívateľov %1$s v téme zo záložiek:',
	),
	'NOTIFICATION_FORUM'				=> '<em>Fórum:</em> %1$s',
	'NOTIFICATION_GROUP_REQUEST'		     => '<strong>Požiadavka na pripojenie sa ku skupine</strong> %2$s od užívateľa %1$s.',
	'NOTIFICATION_GROUP_REQUEST_APPROVED'	=> 'Požiadavka na pripojenie sa ku skupine %1$s <strong>schválená</strong>.',
	'NOTIFICATION_PM'					=> '<strong>Súkromná správa</strong> od užívateľa %1$s:',
	'NOTIFICATION_POST'					=> array(
		1	=> '<strong>Nový príspevok</strong> od užívateľa %1$s v téme:',
          2	=> '<strong>Nové príspevky</strong> od užívateľov %1$s v téme:',
          3	=> '<strong>Nové príspevky</strong> od užívateľov %1$s v téme:',
	),
	'NOTIFICATION_POST_APPROVED'		=> 'Uverejnenie príspevku <strong>schválené</strong>:',
	'NOTIFICATION_POST_DISAPPROVED'	=> 'Uverejnenie príspevku <strong>zamietnuté</strong>:',
	'NOTIFICATION_POST_IN_QUEUE'		=> '<strong>Požiadavka na posúdenie uverejnenia príspevku</strong> od užívateľa %1$s:',
	'NOTIFICATION_QUOTE'				=> array(
		1	=> '<strong>Uverejnená citácia</strong> vášho príspevku užívateľom %1$s v:',
          2	=> '<strong>Uverejnená citácia</strong> vášho príspevku užívateľmi %1$s v:',
          3	=> '<strong>Uverejnená citácia</strong> vášho príspevku užívateľmi %1$s v:',
	),
	'NOTIFICATION_REFERENCE'			=> '"%1$s"',
	'NOTIFICATION_REASON'			=> '<em>Dôvod:</em> %1$s.',
	'NOTIFICATION_REPORT_PM'			=> '<strong>Odoslaná sťažnosť na súkromnú správu</strong> užívateľom %1$s:',
	'NOTIFICATION_REPORT_POST'		=> '<strong>Odoslaná sťažnosť na uverejnený príspevok</strong> užívateľom %1$s:',
	'NOTIFICATION_REPORT_CLOSED'		=> '<strong>Sťažnosť uzavretá</strong> užívateľom %1$s v:',
	'NOTIFICATION_TOPIC'			=> '<strong>Nové téma</strong> od užívateľa %1$s:',
	'NOTIFICATION_TOPIC_APPROVED'		=> 'Uverejnenie témy <strong>schválené</strong>:',
	'NOTIFICATION_TOPIC_DISAPPROVED'	=> 'Uverejnenie témy <strong>zamietnuté</strong>:',
	'NOTIFICATION_TOPIC_IN_QUEUE'		=> '<strong>Požiadavka na posúdenie uverejnenia témy</strong> od užívateľa %1$s:',
	'NOTIFICATION_TYPE_NOT_EXIST'		=> 'Typ upozornenia "%s" nebol v súborovom systéme nájdený alebo chýba.',
	'NOTIFICATION_ADMIN_ACTIVATE_USER'	=> '<strong>Požiadavka na aktiváciu účtu</strong> pre novo registrovaného užívateľa: “%1$s”',
	// Used in conjuction with NOTIFICATION_BOOKMARK and NOTIFICATION_POST.
	'NOTIFICATION_MANY_OTHERS'			=> 'ďalší',
	'NOTIFICATION_X_OTHERS'				=> array(
		1	=> '%d ďalšieho',
          2	=> '%d ďaľších',
          3	=> '%d ďalších',
	),
	'NOTIFY_ADMIN'				=> 'Upozornite prosím administrátorov portálu.',
	'NOTIFY_ADMIN_EMAIL'		=> 'Upozornite prosím administrátorov portálu: <a href="mailto:%1$s">%1$s</a>',
	'NO_ACCESS_ATTACHMENT'		=> 'Nemáte dostatočné oprávenia na prístup k tomuto súboru.',
	'NO_ACTION'				=> 'Nebola zvolená žiadna akcia.',
	'NO_ADMINISTRATORS'			=> 'Tento portál nemá administrátorov.',
	'NO_AUTH_ADMIN'			=> 'Nemáte dostatočné oprávnenia na prístup k ovládaciemu panelu administrátora.',
	'NO_AUTH_ADMIN_USER_DIFFER'	=> 'Nemôžete znovu aktivovať iného užívateľa.',
	'NO_AUTH_OPERATION'			=> 'Nemáte dostatočné oprávnenia na vykonanie tejto operácie.',
	'NO_AVATARS'				=> 'Momentálne nie sú dostupné žiadne avatary',
	'NO_CONNECT_TO_SMTP_HOST'	=> 'Nie je možné sa pripojiť k SMTP serveru : %1$s : %2$s',
	'NO_BIRTHDAYS'				=> 'Dnes nikto neoslavuje narodeniny.',
	'NO_EMAIL_MESSAGE'			=> 'Emailová správa bola prázdna.',
	'NO_EMAIL_RESPONSE_CODE'	     => 'Server neodpovedá.',
	'NO_EMAIL_SUBJECT'			=> 'Nebol zadaný predmet správy.',
	'NO_FORUM'				=> 'Zvolené fórum nie je dostupné.',
	'NO_FORUMS'				=> 'ŽIADNE FÓRA.',
	'NO_GROUP'				=> 'Požadovaná skupina nie je dostupná alebo neexistuje.',
	'NO_GROUP_MEMBERS'			=> 'Táto skupina nemá žiadnych členov.',
	'NO_IPS_DEFINED'			=> 'Neboli definované žiadne IP adresy ani názvy hostiteľov',
	'NO_MEMBERS'				=> 'Podľa zadaných kritérií nebol nájdený žiaden užívateľ.',
	'NO_MESSAGES'				=> 'Žiadne správy',
	'NO_MODE'					=> 'Nebol určený režim.',
	'NO_MODERATORS'			=> 'Tento portál nemá určených moderátorov.',
	'NO_NEW_MESSAGES'			=> 'Žiadne nové správy',
	'NO_NEW_POSTS'				=> 'Žiadne nové príspevky',	// Not used anymore
	'NO_ONLINE_USERS'			=> 'Nikto',
	'NO_POSTS'				=> 'ŽIADNE PRÍSPEVKY',
	'NO_POSTS_TIME_FRAME'		=> 'Vo zvolenom časovom období neboli uverejnené žiadne príspevky.',
	'NO_FEED_ENABLED'			=> 'Tento portál nepodporuje exportovanie.',
	'NO_FEED'					=> 'Požadovaný export nie je dostupný.',
	'NO_STYLE_DATA'			=> 'Nedajú sa získať dáta štýlu',
	'NO_SUBJECT'				=> 'Bez predmetu',								// Used for posts having no subject defined but displayed within management pages.
	'NO_SUCH_SEARCH_MODULE'		=> 'Zvolený spôsob vyhľadávania neexistuje.',
	'NO_SUPPORTED_AUTH_METHODS'	=> 'Žiadne podporované metódy autentifikácie.',
	'NO_TOPIC'				=> 'Požadovaná téma neexistuje.',
	'NO_TOPIC_FORUM'			=> 'Téma alebo fórum viac neexistuje.',
	'NO_TOPICS'				=> 'V tomto fóre nie sú žiadne témy ani príspevky.',
	'NO_TOPICS_TIME_FRAME'		=> 'Pre zvolené časové obdobie neboli nájdené žiadne relevantné výsledky.',
	'NO_UNREAD_POSTS'			=> 'Všetky príspevky už boli prečítané. Neexistuje žiaden nový neprečítaný príspevok',
	'NO_UPLOAD_FORM_FOUND'		=> 'Odovzdávanie začalo, ale nebol nájdený žiaden platný spôsob pre odovzdávanie súborov.',
	'NO_USER'					=> 'Požadovaný užívateľ neexistuje.',
	'NO_USERS'				=> 'Požadovaní užívatelia neexistujú.',
	'NO_USER_SPECIFIED'			=> 'Nebolo zadané žiadne užívateľské meno.',

	// Nullar/Singular/Plural language entry. The key numbers define the number range in which a certain grammatical expression is valid.
	'NUM_ATTACHMENTS'		=> array(
		1	=> '%d príloha',
          2	=> '%d prílohy',
		3	=> '%d príloh',
	),
	'NUM_POSTS_IN_QUEUE'		=> array(
		0	=> 'Žiaden príspevok v poradí',		// 0
		1	=> '1 príspevok v poradí',		// 1
		2	=> '%d príspevky v poradí',		// 2+
          3    => '%d príspevkov v poradí',		// 2+              
	),

	'OCCUPATION'				=> 'Zamestnanie',
	'OFFLINE'					=> 'Offline',
	'ONLINE'					=> 'Online',
	'ONLINE_BUDDIES'			=> 'Priatelia online',
	// "... :: x registered and y hidden"
	'ONLINE_USERS_TOTAL'		=> array(
		1	=> 'Celkom je tu <strong>%1$d</strong> užívateľ %2$s %3$s',
		2	=> 'Celkom je tu <strong>%1$d</strong> užívatelia %2$s %3$s',
          3	=> 'Celkom je tu <strong>%1$d</strong> užívateľov %2$s %3$s',
	),
	// "... :: x registered, y hidden and z guests"
	'ONLINE_USERS_TOTAL_GUESTS'	=> array(
		1	=> 'Momentálne je tu <strong>%1$d</strong> užívateľ %2$s %3$s %4$s',
		2	=> 'Momentálne sú tu <strong>%1$d</strong> užívatelia %2$s %3$s %4$s',
          3	=> 'Momentálne je tu <strong>%1$d</strong> užívateľov %2$s %3$s %4$s',
	),
	'OPTIONS'				=> 'Možnosti',

	'PAGE_OF'				=> 'Strana <strong>%1$d</strong> z <strong>%2$d</strong>',
	'PAGE_TITLE_NUMBER'		=> 'Strana %s',
	'PASSWORD'			=> 'Heslo',
	'PIXEL'				=> 'px',
	'PIXELS'				=> array(
		1	=> '%dpx',
          2	=> '%dpx',
          3	=> '%dpx',
	),
	'PLAY_QUICKTIME_FILE'	=> 'Prehrať súbor QuickTime',
	'PLEASE_WAIT'			=> 'Prosím čakajte.',
	'PM'					=> 'PM',
	'PM_REPORTED'			=> 'Kliknite pre zobrazenie záznamu',
	'POSTING_MESSAGE'		=> 'Píše správu v %s',
	'POSTING_PRIVATE_MESSAGE'	=> 'Píše súkromnú správu',
	'POST'					=> 'Príspevok',
	'POST_ANNOUNCEMENT'		=> 'Oznámenie',
	'POST_STICKY'			=> 'Téma pripnutá na začiatok',
	'POSTED'				=> 'Napísané',
	'POSTED_IN_FORUM'		=> 'v',
	'POSTED_ON_DATE'		=> 'dňa',
	'POSTS'				=> 'Príspevky',
	'POSTS_UNAPPROVED'		=> 'Uverejnenie najmenej jedného príspevku v tejto téme bolo zamietnuté.',
	'POSTS_UNAPPROVED_FORUM' => 'Uverejnenie najmenej jedného príspevku v tomto fóre bolo zamietnuté.',
	'POST_BY_AUTHOR'		=> 'od užívateľa',
	'POST_BY_FOE'			=> '<strong>%1$s</strong>, Ktorý je na vo vašom zozname ignorovaných, uverejnil tento príspevok.',
	'POST_DISPLAY'			=> '%1$sZobraziť tento príspevok%2$s.',
	'POST_DAY'			=> '%.2f príspevkov za deň',
	'POST_DELETED_ACTION'	=> 'Vymazať príspevok:',
	'POST_DELETED'			=> 'Tento príspevok bol vymazaný.',
	'POST_DELETED_BY'		=> '<strong>%2$s</strong> zmazal %3$s príspevok užívateľa <strong>%1$s</strong>.',
	'POST_DELETED_BY_REASON' => '<strong>%2$s</strong> zmazal %3$s príspevok užívateľa <strong>%1$s</strong> z dôvodu: %4$s',
	'POST_DETAILS'			=> 'Detaily príspevku',
	'POST_NEW_TOPIC'		=> 'Vložiť nový príspevok',
	'POST_PCT'			=> '%.2f%% všetkých príspevkov',
	'POST_PCT_ACTIVE'		=> '%.2f%% užívateľovych príspevkov',
	'POST_PCT_ACTIVE_OWN'	=> '%.2f%% vašich príspevkov',
	'POST_REPLY'			=> 'Napísať odpoveď',
	'POST_REPORTED'		=> 'Stlačte pre zobrazenie záznamu',
	'POST_SUBJECT'			=> 'Predmet príspevku',
	'POST_TIME'			=> 'Čas odoslania príspevku',
	'POST_TOPIC'			=> 'Napísať novú tému',
	'POST_UNAPPROVED_ACTION'	=> 'Príspevok čaká na schválenie:',
	'POST_UNAPPROVED'		=> 'Uverejnenie tohoto príspevku bolo zamietnuté.',
	'POWERED_BY'			=> 'Založené na %s',
	'PREVIEW'				=> 'Náhľad',
	'PREVIOUS'			=> 'Predchádzajúci',		// Used in pagination
	'PREVIOUS_STEP'		=> 'Predchádzajúci krok',
	'PRIVACY'				=> 'Ochrana súkromia',
	'PRIVATE_MESSAGE'		=> 'Súkromná správa',
	'PRIVATE_MESSAGES'		=> 'Súkromné správy',
	'PRIVATE_MESSAGING'		=> 'Súkromné správy',
	'PROFILE'				=> 'Moje nastavenia',

	'QUICK_LINKS'			=> 'Rýchle odkazy',

	'RANK'					=> 'Hodnosť',
	'READING_FORUM'			=> 'Číta fórum v %s',
	'READING_GLOBAL_ANNOUNCE'	=> 'Číta oznámenie pre celý portál',
	'READING_LINK'				=> 'Číta fórum odkazov %s',
	'READING_TOPIC'			=> 'Číta tému v %s',
	'READ_PROFILE'				=> 'Môj profil',
	'REASON'					=> 'Dôvod',
	'RECORD_ONLINE_USERS'		=> 'Maximálny počet prítomných: <strong>%1$s</strong>, %2$s',
	'REDIRECT'				=> 'Presmerovať',
	'REDIRECTS'				=> 'Celkom presmerovaní',
	'REGISTER'				=> 'Vytvoriť účet',
	'REGISTERED_USERS'			=> 'Prítomní členovia:',
	// "... and 2 hidden users online"
	'REG_USERS_ONLINE'			=> array(
		1	=> 'Prítomnosť na fóre: %1$d registrovaný %2$s',
		2	=> 'Prítomnosť na fóre: %1$d registrovaní %2$s',
          3    => 'Prítomnosť na fóre: %1$d registrovaných %2$s'
	),
	'REG_USERS_TOTAL'			=> array(
		0	=> '',
		1	=> '| %d registrovaný',
		2	=> '| %d registrovaní',
          3    => '| %d registrovaných',
	),
	'REMOVE'					=> 'Odstrániť',
	'REMOVE_INSTALL'			=> 'Predtým, než začnete používať portál zmažte, presuňte alebo premenujte priečinok “install”. Pokiaľ to nevykonáte po zadaní adresy portálu bude prístupný len administrátorský panel.',
	'REPLIES'					=> 'Odpovedí',
	'REPLY_WITH_QUOTE'			=> 'Odpovedať s citáciou',
	'REPLYING_GLOBAL_ANNOUNCE'	=> 'Odpovedá na oznámenie pre celý portál',
	'REPLYING_MESSAGE'			=> 'Odpovedá na správu in %s',
	'REPORT_BY'				=> 'Oznámil',
	'REPORT_POST'				=> 'Odsoslať sťažnosť na tento príspevok',
	'REPORTING_POST'			=> 'Odosiela sťažnosť na príspevok',
	'RESEND_ACTIVATION'			=> 'Znovu odoslať email s pokynmi pre aktiváciu účtu',
	'RESET'					=> 'Resetovať',
	'RESTORE_PERMISSIONS'		=> 'Obnoviť pôvodné oprávnenia',
	'RETURN_INDEX'				=> '%sZobraziť fórum%s',
	'RETURN_FORUM'				=> '%sVrátiť sa na naposledy navštívené fórum%s',
	'RETURN_PAGE'				=> '%sVrátiť sa na predchádzajúcu stránku%s',
	'RETURN_TOPIC'				=> '%sVrátiť sa na naposledy navštívenú tému%s',
	'RETURN_TO'				=> 'Návrat na "%s"',
	'RETURN_TO_INDEX'			=> 'Návrat na obsah portálu',
	'FEED'					=> 'Feed',
	'FEED_NEWS'				=> 'Novinky',
	'FEED_TOPICS_ACTIVE'		=> 'Aktívne témy',
	'FEED_TOPICS_NEW'			=> 'Nové témy',
	'RULES_ATTACH_CAN'			=> 'V tomto fóre <strong>môžete</strong> vkladať prílohy',
	'RULES_ATTACH_CANNOT'		=> 'V tomto fóre <strong>nemôžete</strong> vkladať prílohy',
	'RULES_DELETE_CAN'			=> 'V tomto fóre <strong>môžete</strong> mazať vlastné príspevky',
	'RULES_DELETE_CANNOT'		=> 'V tomto fóre <strong>nemôžete</strong> mazať vlastné príspevky',
	'RULES_DOWNLOAD_CAN'		=> 'V tomto fóre <strong>môžete</strong> sťahovať prílohy',
	'RULES_DOWNLOAD_CANNOT'		=> 'V tomto fóre <strong>nemôžete</strong> sťahovať prílohy',
	'RULES_EDIT_CAN'			=> 'V tomto fóre <strong>môžete</strong> upravovať vlastné príspevky',
	'RULES_EDIT_CANNOT'			=> 'V tomto fóre <strong>nemôžete</strong> upravovať vlastné príspevky',
	'RULES_LOCK_CAN'			=> 'V tomto fóre <strong>môžete</strong>  zamykať vlastné príspevky',
	'RULES_LOCK_CANNOT'			=> 'V tomto fóre <strong>nemôžete</strong> zamykať vlastné príspevky',
	'RULES_POST_CAN'			=> 'V tomto fóre <strong>môžete</strong> zakladať témy',
	'RULES_POST_CANNOT'			=> 'V tomto fóre <strong>nemôžete</strong> zakladať témy',
	'RULES_REPLY_CAN'			=> 'V tomto fóre <strong>môžete</strong> odpovedať v témach',
	'RULES_REPLY_CANNOT'		=> 'V tomto fóre <strong>nemôžete</strong> odpovedať v témach',
	'RULES_VOTE_CAN'			=> 'V tomto fóre <strong>môžete</strong> hlasovať',
	'RULES_VOTE_CANNOT'			=> 'V tomto fóre <strong>nemôžete</strong> hlasovať',

	'SEARCH'					=> 'Hľadať',
	'SEARCH_MINI'				=> 'Hľadať…',
	'SEARCH_ADV'				=> 'Rozšírené vyhľadávanie',
	'SEARCH_ADV_EXPLAIN'		=> 'Zobraziť rozšírené možnosti vyhľadávania',
	'SEARCH_KEYWORDS'			=> 'Hľadať slová/výraz',
	'SEARCHING_FORUMS'			=> 'Vyhľadáva vo fórach',
	'SEARCH_ACTIVE_TOPICS'		=> 'Aktívne témy',
	'SEARCH_FOR'				=> 'Vyhľadať',
	'SEARCH_FORUM'				=> 'Hľadať v tomto fóre…',
	'SEARCH_NEW'				=> 'Nové príspevky',
	'SEARCH_POSTS_BY'			=> 'Hľadať príspevky podľa',
	'SEARCH_SELF'				=> 'Moje príspevky',
	'SEARCH_TOPIC'				=> 'Hľadať v tejto téme…',
	'SEARCH_UNANSWERED'			=> 'Temy bez odpovedí',
	'SEARCH_UNREAD'			=> 'Neprečítané príspevky',
	'SEARCH_USER_POSTS'			=> 'Príspevky užívateľa',
	'SECONDS'					=> 'Seconds',
	'SEE_ALL'					=> 'Zobraziť všetky',
	'SELECT'					=> 'Vybrať',
	'SELECT_ALL_CODE'			=> 'Vybrať všetko',
	'SELECT_DESTINATION_FORUM'	=> 'Prosím zvoľte cieľové fórum',
	'SELECT_FORUM'				=> 'Vyberte fórum',
	'SEND_EMAIL'				=> 'Odoslať email',				// Used for submit buttons
	'SEND_EMAIL_USER'			=> 'Odoslať email užívateľovi %s',
	'SEND_PRIVATE_MESSAGE'		=> 'Odoslať súkromnú správu',
	'SETTINGS'				=> 'Nastavenia',
	'SIGNATURE'				=> 'Podpis',
	'SKIP'					=> 'Prejsť na obsah',
	'SKYPE'					=> 'Skype',
	'SMTP_NO_AUTH_SUPPORT'		=> 'SMTP server nepodporuje overovanie identity.',
	'SORRY_AUTH_READ'			=> 'Nemáte oprávenenia na zobrazenie tohoto fóra.',
	'SORRY_AUTH_VIEW_ATTACH'	     => 'Nemáte dostatočné oprávnenia na stiahnutie tejto prílohy.',
	'SORT_BY'					=> 'Zoradiť podľa',
	'SORT_JOINED'				=> 'dátumu registrácie',
	'SORT_LOCATION'			=> 'bydliska',
	'SORT_RANK'				=> 'hodnosti',
	'SORT_POSTS'				=> 'príspevkov',
	'SORT_TOPIC_TITLE'			=> 'názvu témy',
	'SORT_USERNAME'			=> 'užívateľského mena',
	'SPLIT_TOPIC'				=> 'Rozdeliť tému',
	'SQL_ERROR_OCCURRED'		=> 'Chyba SQL. Kontaktujte prosím %sadministrátorov portálu%s ak tento problém pretrváva.',
	'STATISTICS'				=> 'Štatistiky',
	'START_WATCHING_FORUM'		=> 'Sledovať toto fórum',
	'START_WATCHING_TOPIC'		=> 'Sledovať túto tému',
	'STOP_WATCHING_FORUM'		=> 'Nesledovať toto fórum',
	'STOP_WATCHING_TOPIC'		=> 'Nesledovať túto tému',
	'STRING_LIST_MULTI'			=> '%1$s, a %2$s',
	'STRING_LIST_SIMPLE'		=> '%1$s a %2$s',
	'SUBFORUM'				=> 'Subfórum',
	'SUBFORUMS'				=> 'Subfóra',
	'SUBJECT'					=> 'Predmet',
	'SUBMIT'					=> 'Odoslať',

	'TB'				=> 'TB',
	'TERMS_USE'		=> 'Podmienky používania',
	'TEST_CONNECTION'	=> 'Test pripojenia',
	'THE_TEAM'			=> 'Realizačný tím',
	'TIB'				=> 'TB',
	'TIME'				=> 'Čas',
	'TIMEOUT_PROCESSING_REQ'			=> 'Čas vypršal.',

	'TOO_LARGE'					=> 'Hodnota, ktorú ste vložili, je príliš veľká.',
	'TOO_LARGE_MAX_RECIPIENTS'		=> 'Hodnota pre <strong>Maximálny počet povolených adresátov jednej súkromnej správy</strong> je príliš veľká.',

	'TOO_LONG'					=> 'Hodnota, ktorú ste vložili, je príliš dlhá.',

	'TOO_LONG_CONFIRM_CODE'			=> 'Potrdzovací kód, ktorý ste vložili, je príliš dlhý.',
	'TOO_LONG_DATEFORMAT'			=> 'Dátumový formát, ktorý ste vložili, je príliš dlhý.',
	'TOO_LONG_JABBER'				=> 'Užívateľské meno pre účet Jabber, ktoré ste vložili, je príliš dlhé.',
	'TOO_LONG_NEW_PASSWORD'			=> 'Nové heslo, ktoré ste vložili, je príliš dlhé.',
	'TOO_LONG_PASSWORD_CONFIRM'		=> 'Potvrdenie hesla, ktoré ste vložili, je príliš dlhé.',
	'TOO_LONG_USER_PASSWORD'		     => 'Heslo, ktoré ste vložili, je príliš dlhé.',
	'TOO_LONG_USERNAME'				=> 'Užívateľské meno, ktoré ste vložili, je príliš dlhé.',
	'TOO_LONG_EMAIL'				=> 'Emailová adresa, ktorú ste vložili, je príliš dlhá.',

	'TOO_MANY_VOTE_OPTIONS'			=> 'Označili ste príliš veľa hlasovacích možností.',

	'TOO_SHORT'					=> 'Hodnota, ktorú ste vložili, je príliš krátka.',

	'TOO_SHORT_CONFIRM_CODE'		     => 'Potrdzovací kód, ktorý ste vložili, je príliš krátky.',
	'TOO_SHORT_DATEFORMAT'			=> 'Dátumový formát, ktorý ste vložili, je príliš krátky.',
	'TOO_SHORT_JABBER'				=> 'Užívateľské meno pre účet Jabber, ktoré ste vložili, je príliš krátke.',
	'TOO_SHORT_NEW_PASSWORD'		     => 'Nové heslo, ktoré ste vložili, je príliš krátke.',
	'TOO_SHORT_PASSWORD_CONFIRM'	     => 'Potvrdenie hesla, ktoré ste vložili, je príliš krátke.',
	'TOO_SHORT_USER_PASSWORD'		=> 'Heslo, ktoré ste vložili, je príliš krátke.',
	'TOO_SHORT_USERNAME'			=> 'Užívateľské meno, ktoré ste vložili, je príliš krátke.',
	'TOO_SHORT_EMAIL'				=> 'Emailová adresa, ktorú ste vložili, je príliš krátka.',
	'TOO_SHORT_EMAIL_CONFIRM'		=> 'Potvrdenie emailovej adresy, ktoré ste vložili, je príliš krátke.',
	'TOO_SMALL'					=> 'Hodnota, ktorú ste vložili je príliš malá.',
	'TOO_SMALL_MAX_RECIPIENTS'		=> 'Hodnota pre <strong>Maximálny počet povolených adresátov jednej súkromnej správy</strong> je príliš malá.',

	'TOPIC'			=> 'Téma',
	'TOPICS'			=> 'Témy',
	'TOPICS_UNAPPROVED'	=> 'Uverejnenie najmenej jednej témy v tomto fóre bolo zamietnuté.',
	'TOPIC_ICON'		=> 'Ikona pre tému',
	'TOPIC_LOCKED'		=> 'Téma je zamknutá, nemôžete editovať príspevky ani písať nové.',
	'TOPIC_LOCKED_SHORT'=> 'Zamknutá téma',
	'TOPIC_MOVED'		=> 'Presunutá téma',
	'TOPIC_REVIEW'		=> 'Prehľad témy',
	'TOPIC_TITLE'		=> 'Názov témy',
	'TOPIC_UNAPPROVED'	=> 'Uverejnenie tejto témy bolo zamietnuté.',
	'TOPIC_DELETED'	=> 'Táto téma bola vymazaná.',
	'TOTAL_ATTACHMENTS'	=> 'príloha(y)',
	'TOTAL_LOGS'		=> array(
		1	=> '%d záznam',
		2	=> '%d záznamy',
          3	=> '%d záznamov',
	),
	'TOTAL_PMS'		=> array(
		1	=> '%d PMka',
		2	=> '%d PMky',
          3	=> '%d PMiek',
	),
	'TOPIC_POLL'		=> 'V tejto téme je hlasovanie.',
	'TOTAL_POSTS'		=> 'Počet príspevkov',
	'TOTAL_POSTS_COUNT'	=> array(
		1	=> '<strong>%d</strong> príspevok',
          2	=> '<strong>%d</strong> príspevky',
          3	=> '<strong>%d</strong> príspevkov',
	),
	'TOPIC_REPORTED'	=> 'Táto téma bola nahlásená',
	'TOTAL_TOPICS'		=> array(
		1	=> '<strong>%d</strong> téma',
          2	=> '<strong>%d</strong> témy',
          3	=> '<strong>%d</strong> tém',
	),
	'TOTAL_USERS'		=> array(
		1	=> '<strong>%d</strong> užívateľ',
          2	=> '<strong>%d</strong> užívatelia',
          3	=> '<strong>%d</strong> užívateľov',
	),
	'TRACKED_PHP_ERROR'	=> 'Zaznamenaných chýb PHP: %s',
	'TWITTER'			=> 'Twitter',

	'UNABLE_GET_IMAGE_SIZE'	=> 'Nebolo možné získať rozmery obrázku. Skontrolujte správnosť zadanej URL adresy.',
	'UNABLE_TO_DELIVER_FILE' => 'Nebolo možné doručť súbor.',
	'UNKNOWN_BROWSER'		=> 'Prehliadač nerozpoznaný',
	'UNMARK_ALL'			=> 'Zrušiť označenia',
	'UNREAD_MESSAGES'		=> 'Neprečítané správy',
	'UNREAD_POST'			=> 'Neprečítaný príspevok',
	'UNREAD_POSTS'			=> 'Neprečítané príspevky',
	'UNWATCH_FORUM_CONFIRM'		=> 'Ste si istý, že chcete prestať sledovať toto fórum?',
	'UNWATCH_FORUM_DETAILED'	     => 'Ste si istý, že chcete prestať sledovať fórum “%s”?',
	'UNWATCH_TOPIC_CONFIRM'		=> 'Ste si istý, že chcete prestať dostávať upozornenia na nové príspevky v tejto téme?',
	'UNWATCH_TOPIC_DETAILED'	     => 'Ste si istý, že chcete prestať dostávať upozornenia na nové príspevky v téme “%s”?',
	'UNWATCHED_FORUMS'			=> 'Už viac nesledujete označené fóra.',
	'UNWATCHED_TOPICS'			=> 'Už viac nebudete upozornený na nové príspevky v tejto téme.',
	'UNWATCHED_FORUMS_TOPICS'	=> 'Sledovanie označených fór a odoberanie upozornení na nové príspevky v označených témach ukončené.',
	'UPDATE'				=> 'Aktualizovať',
	'UPLOAD_IN_PROGRESS'	=> 'Odovzdávanie práve prebieha.',
	'URL_REDIRECT'			=> 'Ak váš prehliadač nepodporuje automatické presmerovanie %skliknite sem%s a budete premerovaný manuálne.',
	'USERGROUPS'			=> 'Skupiny',
	'USERNAME'				=> 'Užívateľské meno',
	'USERNAMES'				=> 'Užívateľské mená',
	'USER_AVATAR'			=> 'Užívateľov profilový obrázok',
	'USER_CANNOT_READ'		=> 'Nemáte dostatočné oprávnenia na zobrazenie príspevkov v tomto fóre.',
	'USER_POSTS'			=> array(
		1	=> '%d príspevok',
		2	=> '%d príspevky',
          3	=> '%d príspevkov',
	),
	'USERS'				=> 'Užívatelia',
	'USE_PERMISSIONS'		=> 'Zobraziť portál v režime s oprávneniami užívateľa',

	'USER_NEW_PERMISSION_DISALLOWED'	=> 'Ospravedlňujeme sa, ale nemáte dostatočné oprávnenia na využitie tejto funkcie. Portál automaticky obmedzuje funkcie užívateľom, ktorí sú na portále zaregistrovaný ešte príliš krátku dobu. Ak chcete uvedenú funkciu využívať, je potrebné vyvinúť väčšiu aktivitu na fóre.',

	'VARIANT_DATE_SEPARATOR'	=> ' / ',	// Used in date format dropdown, eg: "Today, 13:37 / 01 Jan 2007, 13:37" ... to join a relative date with calendar date
	'VIEWED'					=> 'Zobrazené',
	'VIEWED_COUNTS'		=> array(
		1	=> '%d zobrazenie',
		2	=> '%d zobrazenia',
		3	=> '%d zobrazení',
	),
	'VIEWING_CONTACT_ADMIN'		=> 'Prezerá si kontakty na administrátora',
	'VIEWING_FAQ'				=> 'Prezerá si často kladené otázky',
	'VIEWING_MEMBERS'			=> 'Prezerá si informácie o členovi',
	'VIEWING_ONLINE'			=> 'Prezerá si kto je prítomný',
	'VIEWING_MCP'				=> 'Prezerá si moderátorský panel',
	'VIEWING_MEMBER_PROFILE'	     => 'Prezerá si profil člena',
	'VIEWING_PRIVATE_MESSAGES'	=> 'Prezerá si súkromné správy',
	'VIEWING_REGISTER'			=> 'Prezerá si stránku s registráciou',
	'VIEWING_UCP'				=> 'Prezerá si vlasnté nastavenia',
	'VIEWS'					=> 'Zobrazení',
	'VIEW_BOOKMARKS'			=> 'Zobraziť záložky',
	'VIEW_FORUM_LOGS'			=> 'Zobraziť záznamy',
	'VIEW_LATEST_POST'			=> 'Zobraziť posledný príspevok',
	'VIEW_NEWEST_POST'			=> 'Zobraziť prvý neprečítaný príspevok',
	'VIEW_NOTES'				=> 'Zobraziť záznamy užívateľa',
	'VIEW_ONLINE_TIMES'			=> array(
		1	=> 'informácia stará asi %d minútu',
          2	=> 'informácia stará asi %d minúty',
          3	=> 'informácia stará asi %d minút',
	),
	'VIEW_TOPIC'				=> 'Zobraziť tému',
	'VIEW_TOPIC_ANNOUNCEMENT'	=> 'Oznámenie: ',
	'VIEW_TOPIC_GLOBAL'			=> 'Oznámenie pre celý portál: ',
	'VIEW_TOPIC_LOCKED'			=> 'Zamknuté: ',
	'VIEW_TOPIC_LOGS'			=> 'Zobraziť záznamy',
	'VIEW_TOPIC_MOVED'			=> 'Presunuté: ',
	'VIEW_TOPIC_POLL'			=> 'Hlasovanie: ',
	'VIEW_TOPIC_STICKY'			=> 'Téma pripnutá na začiatok zoznamu tém: ',
	'VISIT_WEBSITE'			=> 'Navštíviť webstránku',

	'WARNINGS'			=> 'Výstrahy',
	'WARN_USER'			=> 'Udeliť užívateľovi výstrahu',
	'WATCH_FORUM_CONFIRM'	=> 'Ste si istý, že chcete sledovať toto fórum?',
	'WATCH_FORUM_DETAILED'	=> 'Ste si istý, že chcete sledovať fórum “%s”?',
	'WATCH_TOPIC_CONFIRM'	=> 'Ste si istý, že chcete odoberať upozornenia na nové príspevky v tejto téme?',
	'WATCH_TOPIC_DETAILED'	=> 'Ste si istý, že chcete odoberať upozornenia na nové príspevky v téme “%s”?',
	'WELCOME_SUBJECT'	     => 'Vitajte na fóre %s',
	'WEBSITE'			     => 'Odkaz na vlastný web',
	'WHOIS'				=> 'Kto je',
	'WHO_IS_ONLINE'		=> 'Kto je prítomný',
	'WLM'				=> 'WLM',
	'WRONG_PASSWORD'	     => 'Vložené nesprávne heslo.',

	'WRONG_DATA_COLOUR'			=> 'Nesprávne vložená hodnota farby.',
	'WRONG_DATA_JABBER'			=> 'Nebolo vložené platné užívateľské meno konta Jabber.',
	'WRONG_DATA_LANG'			=> 'Nesprávne zvolený jazyk.',
	'WRONG_DATA_POST_SD'		=> 'Nesprávne zvolený smer zoradenia príspevkov.',
	'WRONG_DATA_POST_SK'		=> 'Nesprávne zvolená možnosť triedenia príspevkov.',
	'WRONG_DATA_TOPIC_SD'		=> 'Nesprávne zvolený smer zoradenia tém.',
	'WRONG_DATA_TOPIC_SK'		=> 'Nesprávne zvolená možnosť triedenia tém.',
	'WROTE'					=> 'napísal',

	'YAHOO'			=> 'Yahoo Messenger',
	'YOUTUBE'			=> 'YouTube',
	'YEAR'			=> 'Rok',
	'YEAR_MONTH_DAY'	=> '(RRRR-MM-DD)',
	'YES'			=> 'Áno',
	'YOU_LAST_VISIT'	=> 'Posledná návšteva: %s',

	'datetime'			=> array(
		'TODAY'		=> 'Dnes',
		'TOMORROW'	=> 'Zajtra',
		'YESTERDAY'	=> 'Včera',
		'AGO'		=> array(
			1		=> 'pred %d minútou',
			2		=> 'pred %d minútami',
               3		=> 'pred %d minútami',
		),

		'Sunday'	     => 'Nedeľa',
		'Monday'	     => 'Pondelok',
		'Tuesday'	     => 'Utorok',
		'Wednesday'	=> 'Streda',
		'Thursday'	=> 'Štvrtok',
		'Friday'	     => 'Piatok',
		'Saturday'	=> 'Sobota',

		'Sun'		=> 'Ne',
		'Mon'		=> 'Po',
		'Tue'		=> 'Ut',
		'Wed'		=> 'St',
		'Thu'		=> 'Št',
		'Fri'		=> 'Pi',
		'Sat'		=> 'So',

		'January'	     => 'Januára',
		'February'	=> 'Februára',
		'March'		=> 'Marca',
		'April'		=> 'Apríla',
		'May'		=> 'Mája',
		'June'		=> 'Júna',
		'July'		=> 'Júla',
		'August'	     => 'Augusta',
		'September'    => 'Septembra',
		'October'	     => 'Októbra',
		'November'	=> 'Novembra',
		'December'	=> 'Decembra',

		'Jan'		=> 'Jan',
		'Feb'		=> 'Feb',
		'Mar'		=> 'Mar',
		'Apr'		=> 'Apr',
		'May_short'	=> 'Máj',	// Short representation of "May". May_short used because in English the short and long date are the same for May.
		'Jun'		=> 'Jún',
		'Jul'		=> 'Júl',
		'Aug'		=> 'Aug',
		'Sep'		=> 'Sep',
		'Oct'		=> 'Okt',
		'Nov'		=> 'Nov',
		'Dec'		=> 'Dec',
	),

	// Timezones can be translated. We use this for the Etc/GMT timezones here,
	// because they are named invers to their offset.
	'timezones'		=> array(
		'UTC'				=> 'UTC',
		'UTC_OFFSET'			=> 'UTC%1$s',
		'UTC_OFFSET_CURRENT'	=> 'UTC%1$s - %2$s',

		'Etc/GMT-12'	=> 'UTC+12',
		'Etc/GMT-11'	=> 'UTC+11',
		'Etc/GMT-10'	=> 'UTC+10',
		'Etc/GMT-9'		=> 'UTC+9',
		'Etc/GMT-8'		=> 'UTC+8',
		'Etc/GMT-7'		=> 'UTC+7',
		'Etc/GMT-6'		=> 'UTC+6',
		'Etc/GMT-5'		=> 'UTC+5',
		'Etc/GMT-4'		=> 'UTC+4',
		'Etc/GMT-3'		=> 'UTC+3',
		'Etc/GMT-2'		=> 'UTC+2',
		'Etc/GMT-1'		=> 'UTC+1',
		'Etc/GMT+1'		=> 'UTC-1',
		'Etc/GMT+2'		=> 'UTC-2',
		'Etc/GMT+3'		=> 'UTC-3',
		'Etc/GMT+4'		=> 'UTC-4',
		'Etc/GMT+5'		=> 'UTC-5',
		'Etc/GMT+6'		=> 'UTC-6',
		'Etc/GMT+7'		=> 'UTC-7',
		'Etc/GMT+8'		=> 'UTC-8',
		'Etc/GMT+9'		=> 'UTC-9',
		'Etc/GMT+10'	=> 'UTC-10',
		'Etc/GMT+11'	=> 'UTC-11',
		'Etc/GMT+12'	=> 'UTC-12',

		'Africa/Abidjan'	=> 'Africa/Abidjan',
		'Africa/Accra'		=> 'Africa/Accra',
		'Africa/Addis_Ababa'	=> 'Africa/Addis Ababa',
		'Africa/Algiers'	=> 'Africa/Algiers',
		'Africa/Asmara'		=> 'Africa/Asmara',
		'Africa/Bamako'		=> 'Africa/Bamako',
		'Africa/Bangui'		=> 'Africa/Bangui',
		'Africa/Banjul'		=> 'Africa/Banjul',
		'Africa/Bissau'		=> 'Africa/Bissau',
		'Africa/Blantyre'	=> 'Africa/Blantyre',
		'Africa/Brazzaville'	=> 'Africa/Brazzaville',
		'Africa/Bujumbura'	=> 'Africa/Bujumbura',
		'Africa/Cairo'		=> 'Africa/Cairo',
		'Africa/Casablanca'	=> 'Africa/Casablanca',
		'Africa/Ceuta'		=> 'Africa/Ceuta',
		'Africa/Conakry'	=> 'Africa/Conakry',
		'Africa/Dakar'		=> 'Africa/Dakar',
		'Africa/Dar_es_Salaam'	=> 'Africa/Dar es Salaam',
		'Africa/Djibouti'	=> 'Africa/Djibouti',
		'Africa/Douala'		=> 'Africa/Douala',
		'Africa/El_Aaiun'	=> 'Africa/El Aaiun',
		'Africa/Freetown'	=> 'Africa/Freetown',
		'Africa/Gaborone'	=> 'Africa/Gaborone',
		'Africa/Harare'		=> 'Africa/Harare',
		'Africa/Johannesburg'	=> 'Africa/Johannesburg',
		'Africa/Juba'		=> 'Africa/Juba',
		'Africa/Kampala'	=> 'Africa/Kampala',
		'Africa/Khartoum'	=> 'Africa/Khartoum',
		'Africa/Kigali'		=> 'Africa/Kigali',
		'Africa/Kinshasa'	=> 'Africa/Kinshasa',
		'Africa/Lagos'		=> 'Africa/Lagos',
		'Africa/Libreville'	=> 'Africa/Libreville',
		'Africa/Lome'		=> 'Africa/Lome',
		'Africa/Luanda'		=> 'Africa/Luanda',
		'Africa/Lubumbashi'	=> 'Africa/Lubumbashi',
		'Africa/Lusaka'		=> 'Africa/Lusaka',
		'Africa/Malabo'		=> 'Africa/Malabo',
		'Africa/Maputo'		=> 'Africa/Maputo',
		'Africa/Maseru'		=> 'Africa/Maseru',
		'Africa/Mbabane'	=> 'Africa/Mbabane',
		'Africa/Mogadishu'	=> 'Africa/Mogadishu',
		'Africa/Monrovia'	=> 'Africa/Monrovia',
		'Africa/Nairobi'	=> 'Africa/Nairobi',
		'Africa/Ndjamena'	=> 'Africa/Ndjamena',
		'Africa/Niamey'		=> 'Africa/Niamey',
		'Africa/Nouakchott'	=> 'Africa/Nouakchott',
		'Africa/Ouagadougou'	=> 'Africa/Ouagadougou',
		'Africa/Porto-Novo'	=> 'Africa/Porto-Novo',
		'Africa/Sao_Tome'	=> 'Africa/Sao Tome',
		'Africa/Tripoli'	=> 'Africa/Tripoli',
		'Africa/Tunis'		=> 'Africa/Tunis',
		'Africa/Windhoek'	=> 'Africa/Windhoek',

		'America/Adak'		=> 'America/Adak',
		'America/Anchorage'	=> 'America/Anchorage',
		'America/Anguilla'	=> 'America/Anguilla',
		'America/Antigua'	=> 'America/Antigua',
		'America/Araguaina'	=> 'America/Araguaina',

		'America/Argentina/Buenos_Aires'	=> 'America/Argentina/Buenos Aires',
		'America/Argentina/Catamarca'	=> 'America/Argentina/Catamarca',
		'America/Argentina/Cordoba'		=> 'America/Argentina/Cordoba',
		'America/Argentina/Jujuy'		=> 'America/Argentina/Jujuy',
		'America/Argentina/La_Rioja'	=> 'America/Argentina/La Rioja',
		'America/Argentina/Mendoza'		=> 'America/Argentina/Mendoza',
		'America/Argentina/Rio_Gallegos'	=> 'America/Argentina/Rio Gallegos',
		'America/Argentina/Salta'		=> 'America/Argentina/Salta',
		'America/Argentina/San_Juan'	=> 'America/Argentina/San Juan',
		'America/Argentina/San_Luis'	=> 'America/Argentina/San Luis',
		'America/Argentina/Tucuman'		=> 'America/Argentina/Tucuman',
		'America/Argentina/Ushuaia'		=> 'America/Argentina/Ushuaia',

		'America/Aruba'			=> 'America/Aruba',
		'America/Asuncion'		=> 'America/Asuncion',
		'America/Atikokan'		=> 'America/Atikokan',
		'America/Bahia'			=> 'America/Bahia',
		'America/Bahia_Banderas'	=> 'America/Bahia Banderas',
		'America/Barbados'		=> 'America/Barbados',
		'America/Belem'			=> 'America/Belem',
		'America/Belize'		=> 'America/Belize',
		'America/Blanc-Sablon'	=> 'America/Blanc-Sablon',
		'America/Boa_Vista'		=> 'America/Boa Vista',
		'America/Bogota'		=> 'America/Bogota',
		'America/Boise'			=> 'America/Boise',
		'America/Cambridge_Bay'	=> 'America/Cambridge Bay',
		'America/Campo_Grande'	=> 'America/Campo Grande',
		'America/Cancun'		=> 'America/Cancun',
		'America/Caracas'		=> 'America/Caracas',
		'America/Cayenne'		=> 'America/Cayenne',
		'America/Cayman'		=> 'America/Cayman',
		'America/Chicago'		=> 'America/Chicago',
		'America/Chihuahua'		=> 'America/Chihuahua',
		'America/Costa_Rica'	=> 'America/Costa Rica',
		'America/Creston'		=> 'America/Creston',
		'America/Cuiaba'		=> 'America/Cuiaba',
		'America/Curacao'		=> 'America/Curacao',
		'America/Danmarkshavn'	=> 'America/Danmarkshavn',
		'America/Dawson'		=> 'America/Dawson',
		'America/Dawson_Creek'	=> 'America/Dawson Creek',
		'America/Denver'		=> 'America/Denver',
		'America/Detroit'		=> 'America/Detroit',
		'America/Dominica'		=> 'America/Dominica',
		'America/Edmonton'		=> 'America/Edmonton',
		'America/Eirunepe'		=> 'America/Eirunepe',
		'America/El_Salvador'	=> 'America/El Salvador',
		'America/Fortaleza'		=> 'America/Fortaleza',
		'America/Glace_Bay'		=> 'America/Glace Bay',
		'America/Godthab'		=> 'America/Godthab',
		'America/Goose_Bay'		=> 'America/Goose Bay',
		'America/Grand_Turk'	=> 'America/Grand Turk',
		'America/Grenada'		=> 'America/Grenada',
		'America/Guadeloupe'	=> 'America/Guadeloupe',
		'America/Guatemala'		=> 'America/Guatemala',
		'America/Guayaquil'		=> 'America/Guayaquil',
		'America/Guyana'		=> 'America/Guyana',
		'America/Halifax'		=> 'America/Halifax',
		'America/Havana'		=> 'America/Havana',
		'America/Hermosillo'		=> 'America/Hermosillo',
		'America/Indiana/Indianapolis'	=> 'America/Indiana/Indianapolis',
		'America/Indiana/Knox'		=> 'America/Indiana/Knox',
		'America/Indiana/Marengo'	=> 'America/Indiana/Marengo',
		'America/Indiana/Petersburg'	=> 'America/Indiana/Petersburg',
		'America/Indiana/Tell_City'	=> 'America/Indiana/Tell City',
		'America/Indiana/Vevay'		=> 'America/Indiana/Vevay',
		'America/Indiana/Vincennes'	=> 'America/Indiana/Vincennes',
		'America/Indiana/Winamac'	=> 'America/Indiana/Winamac',
		'America/Inuvik'		=> 'America/Inuvik',
		'America/Iqaluit'		=> 'America/Iqaluit',
		'America/Jamaica'		=> 'America/Jamaica',
		'America/Juneau'		=> 'America/Juneau',
		'America/Kentucky/Louisville'	=> 'America/Kentucky/Louisville',
		'America/Kentucky/Monticello'	=> 'America/Kentucky/Monticello',
		'America/Kralendijk'	=> 'America/Kralendijk',
		'America/La_Paz'		=> 'America/La Paz',
		'America/Lima'			=> 'America/Lima',
		'America/Los_Angeles'	=> 'America/Los Angeles',
		'America/Lower_Princes'	=> 'America/Lower Princes',
		'America/Maceio'		=> 'America/Maceio',
		'America/Managua'		=> 'America/Managua',
		'America/Manaus'		=> 'America/Manaus',
		'America/Marigot'		=> 'America/Marigot',
		'America/Martinique'	=> 'America/Martinique',
		'America/Matamoros'		=> 'America/Matamoros',
		'America/Mazatlan'		=> 'America/Mazatlan',
		'America/Menominee'		=> 'America/Menominee',
		'America/Merida'		=> 'America/Merida',
		'America/Metlakatla'	=> 'America/Metlakatla',
		'America/Mexico_City'	=> 'America/Mexico City',
		'America/Miquelon'		=> 'America/Miquelon',
		'America/Moncton'		=> 'America/Moncton',
		'America/Monterrey'		=> 'America/Monterrey',
		'America/Montevideo'	=> 'America/Montevideo',
		'America/Montreal'		=> 'America/Montreal',
		'America/Montserrat'	=> 'America/Montserrat',
		'America/Nassau'		=> 'America/Nassau',
		'America/New_York'		=> 'America/New York',
		'America/Nipigon'		=> 'America/Nipigon',
		'America/Nome'			=> 'America/Nome',
		'America/Noronha'		=> 'America/Noronha',
		'America/North_Dakota/Beulah'		=> 'America/North Dakota/Beulah',
		'America/North_Dakota/Center'		=> 'America/North Dakota/Center',
		'America/North_Dakota/New_Salem'	=> 'America/North Dakota/New Salem',
		'America/Ojinaga'		=> 'America/Ojinaga',
		'America/Panama'		=> 'America/Panama',
		'America/Pangnirtung'	=> 'America/Pangnirtung',
		'America/Paramaribo'	=> 'America/Paramaribo',
		'America/Phoenix'		=> 'America/Phoenix',
		'America/Port-au-Prince'	=> 'America/Port-au-Prince',
		'America/Port_of_Spain'	=> 'America/Port of Spain',
		'America/Porto_Velho'	=> 'America/Porto Velho',
		'America/Puerto_Rico'	=> 'America/Puerto Rico',
		'America/Rainy_River'	=> 'America/Rainy River',
		'America/Rankin_Inlet'	=> 'America/Rankin Inlet',
		'America/Recife'		=> 'America/Recife',
		'America/Regina'		=> 'America/Regina',
		'America/Resolute'		=> 'America/Resolute',
		'America/Rio_Branco'	=> 'America/Rio Branco',
		'America/Santa_Isabel'	=> 'America/Santa Isabel',
		'America/Santarem'		=> 'America/Santarem',
		'America/Santiago'		=> 'America/Santiago',
		'America/Santo_Domingo'	=> 'America/Santo Domingo',
		'America/Sao_Paulo'		=> 'America/Sao Paulo',
		'America/Scoresbysund'	=> 'America/Scoresbysund',
		'America/Shiprock'		=> 'America/Shiprock',
		'America/Sitka'			=> 'America/Sitka',
		'America/St_Barthelemy'	=> 'America/St. Barthelemy',
		'America/St_Johns'		=> 'America/St. Johns',
		'America/St_Kitts'		=> 'America/St. Kitts',
		'America/St_Lucia'		=> 'America/St. Lucia',
		'America/St_Thomas'		=> 'America/St. Thomas',
		'America/St_Vincent'	=> 'America/St. Vincent',
		'America/Swift_Current'	=> 'America/Swift Current',
		'America/Tegucigalpa'	=> 'America/Tegucigalpa',
		'America/Thule'			=> 'America/Thule',
		'America/Thunder_Bay'	=> 'America/Thunder Bay',
		'America/Tijuana'		=> 'America/Tijuana',
		'America/Toronto'		=> 'America/Toronto',
		'America/Tortola'		=> 'America/Tortola',
		'America/Vancouver'		=> 'America/Vancouver',
		'America/Whitehorse'	=> 'America/Whitehorse',
		'America/Winnipeg'		=> 'America/Winnipeg',
		'America/Yakutat'		=> 'America/Yakutat',
		'America/Yellowknife'	=> 'America/Yellowknife',

		'Antarctica/Casey'		=> 'Antarctica/Casey',
		'Antarctica/Davis'		=> 'Antarctica/Davis',
		'Antarctica/DumontDUrville'	=> 'Antarctica/DumontDUrville',
		'Antarctica/Macquarie'	=> 'Antarctica/Macquarie',
		'Antarctica/Mawson'		=> 'Antarctica/Mawson',
		'Antarctica/McMurdo'	=> 'Antarctica/McMurdo',
		'Antarctica/Palmer'		=> 'Antarctica/Palmer',
		'Antarctica/Rothera'	=> 'Antarctica/Rothera',
		'Antarctica/South_Pole'	=> 'Antarctica/South Pole',
		'Antarctica/Syowa'		=> 'Antarctica/Syowa',
		'Antarctica/Vostok'		=> 'Antarctica/Vostok',

		'Arctic/Longyearbyen'	=> 'Arctic/Longyearbyen',

		'Asia/Aden'			=> 'Asia/Aden',
		'Asia/Almaty'		=> 'Asia/Almaty',
		'Asia/Amman'		=> 'Asia/Amman',
		'Asia/Anadyr'		=> 'Asia/Anadyr',
		'Asia/Aqtau'		=> 'Asia/Aqtau',
		'Asia/Aqtobe'		=> 'Asia/Aqtobe',
		'Asia/Ashgabat'		=> 'Asia/Ashgabat',
		'Asia/Baghdad'		=> 'Asia/Baghdad',
		'Asia/Bahrain'		=> 'Asia/Bahrain',
		'Asia/Baku'			=> 'Asia/Baku',
		'Asia/Bangkok'		=> 'Asia/Bangkok',
		'Asia/Beirut'		=> 'Asia/Beirut',
		'Asia/Bishkek'		=> 'Asia/Bishkek',
		'Asia/Brunei'		=> 'Asia/Brunei',
		'Asia/Choibalsan'	=> 'Asia/Choibalsan',
		'Asia/Chongqing'	=> 'Asia/Chongqing',
		'Asia/Colombo'		=> 'Asia/Colombo',
		'Asia/Damascus'		=> 'Asia/Damascus',
		'Asia/Dhaka'		=> 'Asia/Dhaka',
		'Asia/Dili'			=> 'Asia/Dili',
		'Asia/Dubai'		=> 'Asia/Dubai',
		'Asia/Dushanbe'		=> 'Asia/Dushanbe',
		'Asia/Gaza'			=> 'Asia/Gaza',
		'Asia/Harbin'		=> 'Asia/Harbin',
		'Asia/Hebron'		=> 'Asia/Hebron',
		'Asia/Ho_Chi_Minh'	=> 'Asia/Ho Chi Minh',
		'Asia/Hong_Kong'	=> 'Asia/Hong Kong',
		'Asia/Hovd'			=> 'Asia/Hovd',
		'Asia/Irkutsk'		=> 'Asia/Irkutsk',
		'Asia/Jakarta'		=> 'Asia/Jakarta',
		'Asia/Jayapura'		=> 'Asia/Jayapura',
		'Asia/Jerusalem'	=> 'Asia/Jerusalem',
		'Asia/Kabul'		=> 'Asia/Kabul',
		'Asia/Kamchatka'	=> 'Asia/Kamchatka',
		'Asia/Karachi'		=> 'Asia/Karachi',
		'Asia/Kashgar'		=> 'Asia/Kashgar',
		'Asia/Kathmandu'	=> 'Asia/Kathmandu',
		'Asia/Khandyga'		=> 'Asia/Khandyga',
		'Asia/Kolkata'		=> 'Asia/Kolkata',
		'Asia/Krasnoyarsk'	=> 'Asia/Krasnoyarsk',
		'Asia/Kuala_Lumpur'	=> 'Asia/Kuala Lumpur',
		'Asia/Kuching'		=> 'Asia/Kuching',
		'Asia/Kuwait'		=> 'Asia/Kuwait',
		'Asia/Macau'		=> 'Asia/Macau',
		'Asia/Magadan'		=> 'Asia/Magadan',
		'Asia/Makassar'		=> 'Asia/Makassar',
		'Asia/Manila'		=> 'Asia/Manila',
		'Asia/Muscat'		=> 'Asia/Muscat',
		'Asia/Nicosia'		=> 'Asia/Nicosia',
		'Asia/Novokuznetsk'	=> 'Asia/Novokuznetsk',
		'Asia/Novosibirsk'	=> 'Asia/Novosibirsk',
		'Asia/Omsk'			=> 'Asia/Omsk',
		'Asia/Oral'			=> 'Asia/Oral',
		'Asia/Phnom_Penh'	=> 'Asia/Phnom Penh',
		'Asia/Pontianak'	=> 'Asia/Pontianak',
		'Asia/Pyongyang'	=> 'Asia/Pyongyang',
		'Asia/Qatar'		=> 'Asia/Qatar',
		'Asia/Qyzylorda'	=> 'Asia/Qyzylorda',
		'Asia/Rangoon'		=> 'Asia/Rangoon',
		'Asia/Riyadh'		=> 'Asia/Riyadh',
		'Asia/Sakhalin'		=> 'Asia/Sakhalin',
		'Asia/Samarkand'	=> 'Asia/Samarkand',
		'Asia/Seoul'		=> 'Asia/Seoul',
		'Asia/Shanghai'		=> 'Asia/Shanghai',
		'Asia/Singapore'	=> 'Asia/Singapore',
		'Asia/Taipei'		=> 'Asia/Taipei',
		'Asia/Tashkent'		=> 'Asia/Tashkent',
		'Asia/Tbilisi'		=> 'Asia/Tbilisi',
		'Asia/Tehran'		=> 'Asia/Tehran',
		'Asia/Thimphu'		=> 'Asia/Thimphu',
		'Asia/Tokyo'		=> 'Asia/Tokyo',
		'Asia/Ulaanbaatar'	=> 'Asia/Ulaanbaatar',
		'Asia/Urumqi'		=> 'Asia/Urumqi',
		'Asia/Ust-Nera'		=> 'Asia/Ust-Nera',
		'Asia/Vientiane'	=> 'Asia/Vientiane',
		'Asia/Vladivostok'	=> 'Asia/Vladivostok',
		'Asia/Yakutsk'		=> 'Asia/Yakutsk',
		'Asia/Yekaterinburg'	=> 'Asia/Yekaterinburg',
		'Asia/Yerevan'		=> 'Asia/Yerevan',

		'Atlantic/Azores'		=> 'Atlantic/Azores',
		'Atlantic/Bermuda'		=> 'Atlantic/Bermuda',
		'Atlantic/Canary'		=> 'Atlantic/Canary',
		'Atlantic/Cape_Verde'	=> 'Atlantic/Cape Verde',
		'Atlantic/Faroe'		=> 'Atlantic/Faroe',
		'Atlantic/Madeira'		=> 'Atlantic/Madeira',
		'Atlantic/Reykjavik'	=> 'Atlantic/Reykjavik',
		'Atlantic/South_Georgia'	=> 'Atlantic/South Georgia',
		'Atlantic/St_Helena'	=> 'Atlantic/St. Helena',
		'Atlantic/Stanley'		=> 'Atlantic/Stanley',

		'Australia/Adelaide'	=> 'Australia/Adelaide',
		'Australia/Brisbane'	=> 'Australia/Brisbane',
		'Australia/Broken_Hill'	=> 'Australia/Broken Hill',
		'Australia/Currie'		=> 'Australia/Currie',
		'Australia/Darwin'		=> 'Australia/Darwin',
		'Australia/Eucla'		=> 'Australia/Eucla',
		'Australia/Hobart'		=> 'Australia/Hobart',
		'Australia/Lindeman'	=> 'Australia/Lindeman',
		'Australia/Lord_Howe'	=> 'Australia/Lord Howe',
		'Australia/Melbourne'	=> 'Australia/Melbourne',
		'Australia/Perth'		=> 'Australia/Perth',
		'Australia/Sydney'		=> 'Australia/Sydney',

		'Europe/Amsterdam'	=> 'Europe/Amsterdam',
		'Europe/Andorra'	=> 'Europe/Andorra',
		'Europe/Athens'		=> 'Europe/Athens',
		'Europe/Belgrade'	=> 'Europe/Belgrade',
		'Europe/Berlin'		=> 'Europe/Berlin',
		'Europe/Bratislava'	=> 'Europe/Bratislava',
		'Europe/Brussels'	=> 'Europe/Brussels',
		'Europe/Bucharest'	=> 'Europe/Bucharest',
		'Europe/Budapest'	=> 'Europe/Budapest',
		'Europe/Busingen'	=> 'Europe/Busingen',
		'Europe/Chisinau'	=> 'Europe/Chisinau',
		'Europe/Copenhagen'	=> 'Europe/Copenhagen',
		'Europe/Dublin'		=> 'Europe/Dublin',
		'Europe/Gibraltar'	=> 'Europe/Gibraltar',
		'Europe/Guernsey'	=> 'Europe/Guernsey',
		'Europe/Helsinki'	=> 'Europe/Helsinki',
		'Europe/Isle_of_Man'	=> 'Europe/Isle of Man',
		'Europe/Istanbul'	=> 'Europe/Istanbul',
		'Europe/Jersey'		=> 'Europe/Jersey',
		'Europe/Kaliningrad'	=> 'Europe/Kaliningrad',
		'Europe/Kiev'		=> 'Europe/Kiev',
		'Europe/Lisbon'		=> 'Europe/Lisbon',
		'Europe/Ljubljana'	=> 'Europe/Ljubljana',
		'Europe/London'		=> 'Europe/London',
		'Europe/Luxembourg'	=> 'Europe/Luxembourg',
		'Europe/Madrid'		=> 'Europe/Madrid',
		'Europe/Malta'		=> 'Europe/Malta',
		'Europe/Mariehamn'	=> 'Europe/Mariehamn',
		'Europe/Minsk'		=> 'Europe/Minsk',
		'Europe/Monaco'		=> 'Europe/Monaco',
		'Europe/Moscow'		=> 'Europe/Moscow',
		'Europe/Oslo'		=> 'Europe/Oslo',
		'Europe/Paris'		=> 'Europe/Paris',
		'Europe/Podgorica'	=> 'Europe/Podgorica',
		'Europe/Prague'		=> 'Europe/Prague',
		'Europe/Riga'		=> 'Europe/Riga',
		'Europe/Rome'		=> 'Europe/Rome',
		'Europe/Samara'		=> 'Europe/Samara',
		'Europe/San_Marino'	=> 'Europe/San Marino',
		'Europe/Sarajevo'	=> 'Europe/Sarajevo',
		'Europe/Simferopol'	=> 'Europe/Simferopol',
		'Europe/Skopje'		=> 'Europe/Skopje',
		'Europe/Sofia'		=> 'Europe/Sofia',
		'Europe/Stockholm'	=> 'Europe/Stockholm',
		'Europe/Tallinn'	=> 'Europe/Tallinn',
		'Europe/Tirane'		=> 'Europe/Tirane',
		'Europe/Uzhgorod'	=> 'Europe/Uzhgorod',
		'Europe/Vaduz'		=> 'Europe/Vaduz',
		'Europe/Vatican'	=> 'Europe/Vatican',
		'Europe/Vienna'		=> 'Europe/Vienna',
		'Europe/Vilnius'	=> 'Europe/Vilnius',
		'Europe/Volgograd'	=> 'Europe/Volgograd',
		'Europe/Warsaw'		=> 'Europe/Warsaw',
		'Europe/Zagreb'		=> 'Europe/Zagreb',
		'Europe/Zaporozhye'	=> 'Europe/Zaporozhye',
		'Europe/Zurich'		=> 'Europe/Zurich',

		'Indian/Antananarivo'	=> 'Indian/Antananarivo',
		'Indian/Chagos'		=> 'Indian/Chagos',
		'Indian/Christmas'	=> 'Indian/Christmas',
		'Indian/Cocos'		=> 'Indian/Cocos',
		'Indian/Comoro'		=> 'Indian/Comoro',
		'Indian/Kerguelen'	=> 'Indian/Kerguelen',
		'Indian/Mahe'		=> 'Indian/Mahe',
		'Indian/Maldives'	=> 'Indian/Maldives',
		'Indian/Mauritius'	=> 'Indian/Mauritius',
		'Indian/Mayotte'	=> 'Indian/Mayotte',
		'Indian/Reunion'	=> 'Indian/Reunion',

		'Pacific/Apia'		=> 'Pacific/Apia',
		'Pacific/Auckland'	=> 'Pacific/Auckland',
		'Pacific/Chatham'	=> 'Pacific/Chatham',
		'Pacific/Chuuk'		=> 'Pacific/Chuuk',
		'Pacific/Easter'	=> 'Pacific/Easter',
		'Pacific/Efate'		=> 'Pacific/Efate',
		'Pacific/Enderbury'	=> 'Pacific/Enderbury',
		'Pacific/Fakaofo'	=> 'Pacific/Fakaofo',
		'Pacific/Fiji'		=> 'Pacific/Fiji',
		'Pacific/Funafuti'	=> 'Pacific/Funafuti',
		'Pacific/Galapagos'	=> 'Pacific/Galapagos',
		'Pacific/Gambier'	=> 'Pacific/Gambier',
		'Pacific/Guadalcanal'	=> 'Pacific/Guadalcanal',
		'Pacific/Guam'		=> 'Pacific/Guam',
		'Pacific/Honolulu'	=> 'Pacific/Honolulu',
		'Pacific/Johnston'	=> 'Pacific/Johnston',
		'Pacific/Kiritimati'	=> 'Pacific/Kiritimati',
		'Pacific/Kosrae'	=> 'Pacific/Kosrae',
		'Pacific/Kwajalein'	=> 'Pacific/Kwajalein',
		'Pacific/Majuro'	=> 'Pacific/Majuro',
		'Pacific/Marquesas'	=> 'Pacific/Marquesas',
		'Pacific/Midway'	=> 'Pacific/Midway',
		'Pacific/Nauru'		=> 'Pacific/Nauru',
		'Pacific/Niue'		=> 'Pacific/Niue',
		'Pacific/Norfolk'	=> 'Pacific/Norfolk',
		'Pacific/Noumea'	=> 'Pacific/Noumea',
		'Pacific/Pago_Pago'	=> 'Pacific/Pago Pago',
		'Pacific/Palau'		=> 'Pacific/Palau',
		'Pacific/Pitcairn'	=> 'Pacific/Pitcairn',
		'Pacific/Pohnpei'	=> 'Pacific/Pohnpei',
		'Pacific/Port_Moresby'	=> 'Pacific/Port Moresby',
		'Pacific/Rarotonga'	=> 'Pacific/Rarotonga',
		'Pacific/Saipan'	=> 'Pacific/Saipan',
		'Pacific/Tahiti'	=> 'Pacific/Tahiti',
		'Pacific/Tarawa'	=> 'Pacific/Tarawa',
		'Pacific/Tongatapu'	=> 'Pacific/Tongatapu',
		'Pacific/Wake'		=> 'Pacific/Wake',
		'Pacific/Wallis'	=> 'Pacific/Wallis',
	),

	// The value is only an example and will get replaced by the current time on view
	'dateformats'	=> array(
          'D, j. F Y, H:i'         => 'So, 1. Januára 2015, 13:37',
          'l, j. F Y, H:i'         => 'Sobota, 1. Januára 2015, 13:37',
          'j. F Y, H:i'            => '1. Januára 2015, 13:37',
          '|D, j. F Y|, H:i'		=> 'Dnes, 13:37 / So, 1. Januára 2015, 13:37',
          '|l, j. F Y|, H:i'		=> 'Dnes, 13:37 / Sobota, 1. Januára 2015, 13:37',
          '|j. F Y|, H:i'		=> 'Dnes, 13:37 / 1. Januára 2015, 13:37',
	),

	// The default dateformat which will be used on new installs in this language
	// Translators should change this if a the usual date format is different
	'default_dateformat'	=> 'j. F Y, H:i', // Mon Jan 01, 2007 1:37 pm

));
